data:
  input_dir: "data/raw/iphone"
  # gt_dir: "data/raw/lol_high"
  output_dir: "data/results/iphone"
algorithms:
  - clahe
  - retinex

clahe:
  clip_limit: 2.0
  tile_grid_size: [8, 8]

retinex:
  sigma_list: [15, 80, 250]
  G: 5.0
  b: 25.0
  alpha: 125.0
  beta: 46.0
  low_clip: 0.01
  high_clip: 0.99
  stretch_color_balance: False

analysis:
  metrics_file: "data/results/iphone/metrics.csv"
  output_dir: "analysis_results/iphone"